apiVersion: v1
kind: Secret
metadata:
  name: my-secrets
type: Opaque
data:
  mongodb-url: bW9uZ29kYjovL3Jvb3Q6cGFzc3dvcmQxMjNAeW9sby1tb25nb2RiLWhlYWRsZXNzOjI3MDE3
  message-broker-url: YW1xcDovL3VzZXIxOnBhc3N3b3JkMTIzQHlvbG8tcmFiYml0bXE6NTY3Mg==
  app-secret: eW9sb19tZWRpYQ==
  bucket-name: eW9sby1idWNrZXQtcHVibGlj
  region: YXAtc291dGgtMQ==
  s3-access-key: QUtJQVpRM0RSSzdBTDdQQ1ZQVlE=
  s3-secret-key: Rm9QRHV0TnhlZWVzcE9JSTlHWDFTaHFlWlV3c3p3aGlqMWd1b3BDMw==
  gmail: c2FjaGluc2FjaHU5NjdAZ21haWwuY29t
  pass: cnJ3eSBqa3l4IHFjb3cgbWNtaw==