apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: sachin967/posts
          ports:
            - containerPort: 7000
          #   env:
          # - name: PORT
          #   value: 7000
          # - name: MONGODB_URL
          #   valueFrom:
          #     secretKeyRef:
          #       name: my-secrets
          #       key: mongodb-url
          # - name: MESSAGE_BROKER_URL
          #   valueFrom:
          #     secretKeyRef:
          #       name: my-secrets
          #       key: message-broker-url
          # - name: APP_SECRET
          #   valueFrom:
          #     secretKeyRef:
          #       name: my-secrets
          #       key: app-secret
          # - name: BUCKET_NAME
          #   valueFrom:
          #     secretKeyRef:
          #       name: my-secrets
          #       key: bucket-name
          # - name: REGION
          #   valueFrom:
          #     secretKeyRef:
          #       name: my-secrets
          #       key: region
          # - name: S3_ACCESS_KEY
          #   valueFrom:
          #     secretKeyRef:
          #       name: my-secrets
          #       key: s3-access-key
          # - name: S3_SECRET_KEY
          #   valueFrom:
          #     secretKeyRef:
          #       name: my-secrets
          #       key: s3-secret-key

---

apiVersion: v1
kind: Service
metadata:
  name: posts
spec:
  ports:
    - port: 7000
      protocol: TCP
      targetPort: 7000
  selector:
    app: posts

