apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: sachin967/admin
          ports:
            - containerPort: 7300
          # env:
          #   - name: PORT
          #     value: 7300
          #   - name: MONGODB_URL
          #     valueFrom:
          #       secretKeyRef:
          #         name: my-secrets
          #         key: mongodb-url
          #   - name: MESSAGE_BROKER_URL
          #     valueFrom:
          #       secretKeyRef:
          #         name: my-secrets
          #         key: message-broker-url
          #   - name: APP_SECRET
          #     valueFrom:
          #       secretKeyRef:
          #         name: my-secrets
          #         key: app-secret
